//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinectV2MouseControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double Smoothing {
            get {
                return ((double)(this["Smoothing"]));
            }
            set {
                this["Smoothing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Mode {
            get {
                return ((int)(this["Mode"]));
            }
            set {
                this["Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double MoveScale {
            get {
                return ((double)(this["MoveScale"]));
            }
            set {
                this["MoveScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double HoverRange {
            get {
                return ((double)(this["HoverRange"]));
            }
            set {
                this["HoverRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double HoverDuration {
            get {
                return ((double)(this["HoverDuration"]));
            }
            set {
                this["HoverDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double SpeedResponsiveness {
            get {
                return ((double)(this["SpeedResponsiveness"]));
            }
            set {
                this["SpeedResponsiveness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double JitterDeadzone {
            get {
                return ((double)(this["JitterDeadzone"]));
            }
            set {
                this["JitterDeadzone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double ClickFreezeDuration {
            get {
                return ((double)(this["ClickFreezeDuration"]));
            }
            set {
                this["ClickFreezeDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double PointerCenterHeight {
            get {
                return ((double)(this["PointerCenterHeight"]));
            }
            set {
                this["PointerCenterHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double ForwardActivationDistance {
            get {
                return ((double)(this["ForwardActivationDistance"]));
            }
            set {
                this["ForwardActivationDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double ActivationMinHeight {
            get {
                return ((double)(this["ActivationMinHeight"]));
            }
            set {
                this["ActivationMinHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double ScrollSpeed {
            get {
                return ((double)(this["ScrollSpeed"]));
            }
            set {
                this["ScrollSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double SwipeMinDisplacement {
            get {
                return ((double)(this["SwipeMinDisplacement"]));
            }
            set {
                this["SwipeMinDisplacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StationaryLockEnabled {
            get {
                return ((bool)(this["StationaryLockEnabled"]));
            }
            set {
                this["StationaryLockEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double StationaryLockRadius {
            get {
                return ((double)(this["StationaryLockRadius"]));
            }
            set {
                this["StationaryLockRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.35")]
        public double StationaryLockDwell {
            get {
                return ((double)(this["StationaryLockDwell"]));
            }
            set {
                this["StationaryLockDwell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double StationaryBreakoutRadius {
            get {
                return ((double)(this["StationaryBreakoutRadius"]));
            }
            set {
                this["StationaryBreakoutRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCalibratedRange {
            get {
                return ((bool)(this["UseCalibratedRange"]));
            }
            set {
                this["UseCalibratedRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double HandRangeX {
            get {
                return ((double)(this["HandRangeX"]));
            }
            set {
                this["HandRangeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double HandRangeY {
            get {
                return ((double)(this["HandRangeY"]));
            }
            set {
                this["HandRangeY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HandCenterX {
            get {
                return ((double)(this["HandCenterX"]));
            }
            set {
                this["HandCenterX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double ScrollCurve {
            get {
                return ((double)(this["ScrollCurve"]));
            }
            set {
                this["ScrollCurve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InvertScroll {
            get {
                return ((bool)(this["InvertScroll"]));
            }
            set {
                this["InvertScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double PointerSettleTime {
            get {
                return ((double)(this["PointerSettleTime"]));
            }
            set {
                this["PointerSettleTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CompactOnMinimize {
            get {
                return ((bool)(this["CompactOnMinimize"]));
            }
            set {
                this["CompactOnMinimize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartCompact {
            get {
                return ((bool)(this["StartCompact"]));
            }
            set {
                this["StartCompact"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OverlayAlwaysOnTop {
            get {
                return ((bool)(this["OverlayAlwaysOnTop"]));
            }
            set {
                this["OverlayAlwaysOnTop"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double OverlayLeft {
            get {
                return ((double)(this["OverlayLeft"]));
            }
            set {
                this["OverlayLeft"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double OverlayTop {
            get {
                return ((double)(this["OverlayTop"]));
            }
            set {
                this["OverlayTop"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverlayChatOpen {
            get {
                return ((bool)(this["OverlayChatOpen"]));
            }
            set {
                this["OverlayChatOpen"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VoiceEnabled {
            get {
                return ((bool)(this["VoiceEnabled"]));
            }
            set {
                this["VoiceEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public double VoiceWakeSensitivity {
            get {
                return ((double)(this["VoiceWakeSensitivity"]));
            }
            set {
                this["VoiceWakeSensitivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double VoiceCommandThreshold {
            get {
                return ((double)(this["VoiceCommandThreshold"]));
            }
            set {
                this["VoiceCommandThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VoiceDismissSound {
            get {
                return ((bool)(this["VoiceDismissSound"]));
            }
            set {
                this["VoiceDismissSound"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VoiceInputDeviceId {
            get {
                return ((string)(this["VoiceInputDeviceId"]));
            }
            set {
                this["VoiceInputDeviceId"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VoiceInputDeviceName {
            get {
                return ((string)(this["VoiceInputDeviceName"]));
            }
            set {
                this["VoiceInputDeviceName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jarvis")]
        public string VoiceWakePhrase {
            get {
                return ((string)(this["VoiceWakePhrase"]));
            }
            set {
                this["VoiceWakePhrase"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Whisper")]
        public string VoiceSpeechEngine
        {
            get { return (string)this["VoiceSpeechEngine"]; }
            set { this["VoiceSpeechEngine"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VoiceListeningClick
        {
            get { return (bool)this["VoiceListeningClick"]; }
            set { this["VoiceListeningClick"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("deepseek-flash")]
        public string AssistantModel
        {
            get { return (string)this["AssistantModel"]; }
            set { this["AssistantModel"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendOtherRequestsToAI
        {
            get { return (bool)this["SendOtherRequestsToAI"]; }
            set { this["SendOtherRequestsToAI"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReloadLastProfile
        {
            get { return (bool)this["ReloadLastProfile"]; }
            set { this["ReloadLastProfile"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LastProfileSlot
        {
            get { return (int)this["LastProfileSlot"]; }
            set { this["LastProfileSlot"] = value; }
        }
    }
}
